# The following is a Python translation of the g_dfovec_1d.m that was largely
# generated by ADiMat 0.5.6-2502

import numpy as np


def adimat_g_pow_left(g_a, a, b):
    z = a**b
    if np.isscalar(a) and np.isscalar(b):
        g_z = g_a * b * (a ** (b - 1))
    elif np.isscalar(b):
        if b == 1:
            g_z = g_a
        elif np.mod(b, 1) == 0 and b > 1:
            g_z = g_a * (a ** (b - 1))
            for i in range(1, int(b) - 1):
                g_z = g_z + (a**i) * g_a * (a ** (b - i - 1))
        else:
            raise ValueError("adimat:adimat_g_pow", "Differentiation of A^b, where A is a square matrix and b is scalar, but not an integer > 1, is not supported.")
    elif np.isscalar(a):
        raise ValueError("adimat:adimat_g_pow", "Differentiation of a^B, where a is scalar and B is a square matrix, is not supported.")
    else:
        raise ValueError("adimat:adimat_g_pow", "A^B, where both X and Y are matrices, is not allowed in Python")

    return g_z, z


def g_dfovec_1d(g_t, t, ind, m, n, g_x, x, nprob):
    # Initialize things:
    fvec = np.zeros(m)
    g_fvec = np.zeros_like(fvec)
    g_sum = 0
    sum_val = 0
    g_tmp_x_00000 = g_x[ind].copy()
    tmp_x_00000 = x[ind].copy()
    g_x[ind] = g_tmp_x_00000 + g_t
    x[ind] = tmp_x_00000 + t

    if nprob == 1:
        for j in range(n):
            g_tmp_x_00001 = g_x[j]
            tmp_x_00001 = x[j]
            g_tmp_dfovec_1d_00191 = g_sum + g_tmp_x_00001
            tmp_dfovec_1d_00191 = sum_val + tmp_x_00001
            g_sum = g_tmp_dfovec_1d_00191
            sum_val = tmp_dfovec_1d_00191

        g_tmp_dfovec_1d_00000 = 2 * g_sum
        tmp_dfovec_1d_00000 = 2 * sum_val
        g_tmp_dfovec_1d_00001 = g_tmp_dfovec_1d_00000 / m
        tmp_dfovec_1d_00001 = tmp_dfovec_1d_00000 / m
        g_temp = g_tmp_dfovec_1d_00001
        temp = tmp_dfovec_1d_00001 + 1

        for i in range(m):
            g_fvec[i] = -g_temp
            fvec[i] = -temp

            if i < n:
                g_tmp_fvec_00000 = g_fvec[i]
                tmp_fvec_00000 = fvec[i]
                g_tmp_x_00002 = g_x[i]
                tmp_x_00002 = x[i]
                g_fvec[i] = g_tmp_fvec_00000 + g_tmp_x_00002
                fvec[i] = tmp_fvec_00000 + tmp_x_00002

    elif nprob == 2:
        for j in range(n):
            g_tmp_x_00003 = g_x[j]
            tmp_x_00003 = x[j]
            g_tmp_dfovec_1d_00002 = (j + 1) * g_tmp_x_00003
            tmp_dfovec_1d_00002 = (j + 1) * tmp_x_00003
            g_tmp_dfovec_1d_00192 = g_sum + g_tmp_dfovec_1d_00002
            tmp_dfovec_1d_00192 = sum_val + tmp_dfovec_1d_00002
            g_sum = g_tmp_dfovec_1d_00192
            sum_val = tmp_dfovec_1d_00192

        for i in range(m):
            g_tmp_dfovec_1d_00003 = (i + 1) * g_sum
            tmp_dfovec_1d_00003 = (i + 1) * sum_val
            g_fvec[i] = g_tmp_dfovec_1d_00003
            fvec[i] = tmp_dfovec_1d_00003 - 1

    elif nprob == 3:
        tmp_dfovec_1d_00004 = n - 1
        for j in range(1, tmp_dfovec_1d_00004):
            g_tmp_x_00004 = g_x[j]
            tmp_x_00004 = x[j]
            g_tmp_dfovec_1d_00005 = (j + 1) * g_tmp_x_00004
            tmp_dfovec_1d_00005 = (j + 1) * tmp_x_00004
            g_tmp_dfovec_1d_00193 = g_sum + g_tmp_dfovec_1d_00005
            tmp_dfovec_1d_00193 = sum_val + tmp_dfovec_1d_00005
            g_sum = g_tmp_dfovec_1d_00193
            sum_val = tmp_dfovec_1d_00193
        tmp_dfovec_1d_00006 = m - 1
        for i in range(tmp_dfovec_1d_00006):
            tmp_dfovec_1d_00007 = i
            g_tmp_dfovec_1d_00008 = tmp_dfovec_1d_00007 * g_sum
            tmp_dfovec_1d_00008 = tmp_dfovec_1d_00007 * sum_val
            g_fvec[i] = g_tmp_dfovec_1d_00008
            fvec[i] = tmp_dfovec_1d_00008 - 1
        fvec[m - 1] = -1
        g_fvec[m - 1] = 0
    elif nprob == 4:
        g_tmp_x_00005 = g_x[1]
        tmp_x_00005 = x[1]
        g_tmp_x_00006 = g_x[0]
        tmp_x_00006 = x[0]
        g_tmp_dfovec_1d_00009 = adimat_g_pow_left(g_tmp_x_00006, tmp_x_00006, 2)[0]
        tmp_dfovec_1d_00009 = tmp_x_00006**2
        g_tmp_dfovec_1d_00010 = g_tmp_x_00005 - g_tmp_dfovec_1d_00009
        tmp_dfovec_1d_00010 = tmp_x_00005 - tmp_dfovec_1d_00009
        g_fvec[0] = 10 * g_tmp_dfovec_1d_00010
        fvec[0] = 10 * tmp_dfovec_1d_00010
        g_tmp_x_00007 = g_x[0]
        tmp_x_00007 = x[0]
        g_fvec[1] = -g_tmp_x_00007
        fvec[1] = 1 - tmp_x_00007
    elif nprob == 5:
        if x[0] > 0:
            g_tmp_x_00008 = g_x[1]
            tmp_x_00008 = x[1]
            g_tmp_x_00009 = g_x[0]
            tmp_x_00009 = x[0]
            tmp_dfovec_1d_00011 = tmp_x_00008 / tmp_x_00009
            g_tmp_dfovec_1d_00011 = (g_tmp_x_00008 - g_tmp_x_00009 * tmp_dfovec_1d_00011) / tmp_x_00009
            g_tmp_atan_00000 = g_tmp_dfovec_1d_00011 / (1 + tmp_dfovec_1d_00011**2)
            tmp_atan_00000 = np.arctan(tmp_dfovec_1d_00011)
            tmp_dfovec_1d_00012 = 2 * np.pi
            g_th = g_tmp_atan_00000 / tmp_dfovec_1d_00012
            th = tmp_atan_00000 / tmp_dfovec_1d_00012
        elif x[0] < 0:
            g_tmp_x_00010 = g_x[1]
            tmp_x_00010 = x[1]
            g_tmp_x_00011 = g_x[0]
            tmp_x_00011 = x[0]
            tmp_dfovec_1d_00013 = tmp_x_00010 / tmp_x_00011
            g_tmp_dfovec_1d_00013 = (g_tmp_x_00010 - g_tmp_x_00011 * tmp_dfovec_1d_00013) / tmp_x_00011
            g_tmp_atan_00001 = g_tmp_dfovec_1d_00013 / (1 + tmp_dfovec_1d_00013**2)
            tmp_atan_00001 = np.arctan(tmp_dfovec_1d_00013)
            tmp_dfovec_1d_00014 = 2 * np.pi
            g_tmp_dfovec_1d_00015 = g_tmp_atan_00001 / tmp_dfovec_1d_00014
            tmp_dfovec_1d_00015 = tmp_atan_00001 / tmp_dfovec_1d_00014
            g_th = g_tmp_dfovec_1d_00015
            th = tmp_dfovec_1d_00015 + 0.5
        else:  # x[0] == 0
            th = 0.25
            g_th = np.zeros_like(th)

        g_tmp_x_00012 = g_x[0]
        tmp_x_00012 = x[0]
        g_tmp_dfovec_1d_00016 = adimat_g_pow_left(g_tmp_x_00012, tmp_x_00012, 2)[0]
        tmp_dfovec_1d_00016 = tmp_x_00012**2
        g_tmp_x_00013 = g_x[1]
        tmp_x_00013 = x[1]
        g_tmp_dfovec_1d_00017 = adimat_g_pow_left(g_tmp_x_00013, tmp_x_00013, 2)[0]
        tmp_dfovec_1d_00017 = tmp_x_00013**2
        g_tmp_dfovec_1d_00018 = g_tmp_dfovec_1d_00016 + g_tmp_dfovec_1d_00017
        tmp_dfovec_1d_00018 = tmp_dfovec_1d_00016 + tmp_dfovec_1d_00017
        r = np.sqrt(tmp_dfovec_1d_00018)
        g_r = g_tmp_dfovec_1d_00018 / (2 * r)
        g_tmp_x_00014 = g_x[2]
        tmp_x_00014 = x[2]
        g_tmp_dfovec_1d_00019 = 10 * g_th
        tmp_dfovec_1d_00019 = 10 * th
        g_tmp_dfovec_1d_00020 = g_tmp_x_00014 - g_tmp_dfovec_1d_00019
        tmp_dfovec_1d_00020 = tmp_x_00014 - tmp_dfovec_1d_00019
        g_fvec[0] = 10 * g_tmp_dfovec_1d_00020
        fvec[0] = 10 * tmp_dfovec_1d_00020
        g_tmp_dfovec_1d_00021 = g_r
        tmp_dfovec_1d_00021 = r - 1
        g_fvec[1] = 10 * g_tmp_dfovec_1d_00021
        fvec[1] = 10 * tmp_dfovec_1d_00021
        g_tmp_x_00015 = g_x[2]
        tmp_x_00015 = x[2]
        g_fvec[2] = g_tmp_x_00015
        fvec[2] = tmp_x_00015
    elif nprob == 6:
        g_tmp_x_00016 = g_x[0]
        tmp_x_00016 = x[0]
        g_tmp_x_00017 = g_x[1]
        tmp_x_00017 = x[1]
        g_tmp_dfovec_1d_00022 = 10 * g_tmp_x_00017
        tmp_dfovec_1d_00022 = 10 * tmp_x_00017
        g_fvec[0] = g_tmp_x_00016 + g_tmp_dfovec_1d_00022
        fvec[0] = tmp_x_00016 + tmp_dfovec_1d_00022
        g_tmp_x_00018 = g_x[2]
        tmp_x_00018 = x[2]
        g_tmp_x_00019 = g_x[3]
        tmp_x_00019 = x[3]
        g_tmp_dfovec_1d_00023 = g_tmp_x_00018 - g_tmp_x_00019
        tmp_dfovec_1d_00023 = tmp_x_00018 - tmp_x_00019
        g_fvec[1] = np.sqrt(5) * g_tmp_dfovec_1d_00023
        fvec[1] = np.sqrt(5) * tmp_dfovec_1d_00023
        g_tmp_x_00020 = g_x[1]
        tmp_x_00020 = x[1]
        g_tmp_x_00021 = g_x[2]
        tmp_x_00021 = x[2]
        g_tmp_dfovec_1d_00024 = 2 * g_tmp_x_00021
        tmp_dfovec_1d_00024 = 2 * tmp_x_00021
        g_tmp_dfovec_1d_00025 = g_tmp_x_00020 - g_tmp_dfovec_1d_00024
        tmp_dfovec_1d_00025 = tmp_x_00020 - tmp_dfovec_1d_00024
        g_fvec[2] = adimat_g_pow_left(g_tmp_dfovec_1d_00025, tmp_dfovec_1d_00025, 2)[0]
        fvec[2] = tmp_dfovec_1d_00025**2
        g_tmp_x_00022 = g_x[0]
        tmp_x_00022 = x[0]
        g_tmp_x_00023 = g_x[3]
        tmp_x_00023 = x[3]
        g_tmp_dfovec_1d_00026 = g_tmp_x_00022 - g_tmp_x_00023
        tmp_dfovec_1d_00026 = tmp_x_00022 - tmp_x_00023
        g_tmp_dfovec_1d_00027 = adimat_g_pow_left(g_tmp_dfovec_1d_00026, tmp_dfovec_1d_00026, 2)[0]
        tmp_dfovec_1d_00027 = tmp_dfovec_1d_00026**2
        g_fvec[3] = np.sqrt(10) * g_tmp_dfovec_1d_00027
        fvec[3] = np.sqrt(10) * tmp_dfovec_1d_00027
    elif nprob == 7:
        c13 = 1.3e1
        c14 = 1.4e1
        c29 = 2.9e1
        g_tmp_x_00024 = g_x[0]
        tmp_x_00024 = x[0]
        g_tmp_x_00025 = g_x[1]
        tmp_x_00025 = x[1]
        g_tmp_dfovec_1d_00028 = -g_tmp_x_00025
        tmp_dfovec_1d_00028 = 5 - tmp_x_00025
        g_tmp_dfovec_1d_00029 = g_tmp_dfovec_1d_00028 * tmp_x_00025 + tmp_dfovec_1d_00028 * g_tmp_x_00025
        tmp_dfovec_1d_00029 = tmp_dfovec_1d_00028 * tmp_x_00025
        g_tmp_dfovec_1d_00030 = g_tmp_dfovec_1d_00029
        tmp_dfovec_1d_00030 = tmp_dfovec_1d_00029 - 2
        g_tmp_dfovec_1d_00031 = g_tmp_dfovec_1d_00030 * tmp_x_00025 + tmp_dfovec_1d_00030 * g_tmp_x_00025
        tmp_dfovec_1d_00031 = tmp_dfovec_1d_00030 * tmp_x_00025
        g_fvec[0] = g_tmp_x_00024 + g_tmp_dfovec_1d_00031
        fvec[0] = -c13 + tmp_x_00024 + tmp_dfovec_1d_00031
        g_tmp_x_00026 = g_x[0]
        tmp_x_00026 = x[0]
        g_tmp_x_00027 = g_x[1]
        tmp_x_00027 = x[1]
        g_tmp_dfovec_1d_00032 = g_tmp_x_00027
        tmp_dfovec_1d_00032 = 1 + tmp_x_00027
        g_tmp_dfovec_1d_00033 = g_tmp_dfovec_1d_00032 * tmp_x_00027 + tmp_dfovec_1d_00032 * g_tmp_x_00027
        tmp_dfovec_1d_00033 = tmp_dfovec_1d_00032 * tmp_x_00027
        g_tmp_dfovec_1d_00034 = g_tmp_dfovec_1d_00033
        tmp_dfovec_1d_00034 = tmp_dfovec_1d_00033 - c14
        g_tmp_dfovec_1d_00035 = g_tmp_dfovec_1d_00034 * tmp_x_00027 + tmp_dfovec_1d_00034 * g_tmp_x_00027
        tmp_dfovec_1d_00035 = tmp_dfovec_1d_00034 * tmp_x_00027
        g_fvec[1] = g_tmp_x_00026 + g_tmp_dfovec_1d_00035
        fvec[1] = -c29 + tmp_x_00026 + tmp_dfovec_1d_00035
    elif nprob == 8:
        y1 = [1.4e-1, 1.8e-1, 2.2e-1, 2.5e-1, 2.9e-1, 3.2e-1, 3.5e-1, 3.9e-1, 3.7e-1, 5.8e-1, 7.3e-1, 9.6e-1, 1.34, 2.1, 4.39]
        for i in range(15):
            tmp1 = i + 1
            g_tmp1 = np.zeros_like(tmp1)
            tmp2 = 16 - tmp1
            g_tmp2 = np.zeros_like(tmp2)
            g_tmp3 = g_tmp1
            tmp3 = tmp1
            if i > 7:
                g_tmp3 = g_tmp2
                tmp3 = tmp2

            g_tmp_x_00028 = g_x[0]
            tmp_x_00028 = x[0]
            g_tmp_x_00029 = g_x[1]
            tmp_x_00029 = x[1]

            g_tmp_dfovec_1d_00036 = g_tmp_x_00029 * tmp2 + tmp_x_00029 * g_tmp2
            tmp_dfovec_1d_00036 = tmp_x_00029 * tmp2
            g_tmp_x_00030 = g_x[2]
            tmp_x_00030 = x[2]

            g_tmp_dfovec_1d_00037 = g_tmp_x_00030 * tmp3 + tmp_x_00030 * g_tmp3
            tmp_dfovec_1d_00037 = tmp_x_00030 * tmp3

            g_tmp_dfovec_1d_00038 = g_tmp_dfovec_1d_00036 + g_tmp_dfovec_1d_00037
            tmp_dfovec_1d_00038 = tmp_dfovec_1d_00036 + tmp_dfovec_1d_00037
            tmp_dfovec_1d_00039 = tmp1 / tmp_dfovec_1d_00038

            g_tmp_dfovec_1d_00039 = (g_tmp1 - np.dot(g_tmp_dfovec_1d_00038.T, tmp_dfovec_1d_00039)) / tmp_dfovec_1d_00038

            g_tmp_dfovec_1d_00040 = g_tmp_x_00028 + g_tmp_dfovec_1d_00039
            tmp_dfovec_1d_00040 = tmp_x_00028 + tmp_dfovec_1d_00039

            g_fvec[i] = -g_tmp_dfovec_1d_00040
            fvec[i] = y1[i] - tmp_dfovec_1d_00040

    elif nprob == 9:
        y2 = [1.957e-1, 1.947e-1, 1.735e-1, 1.6e-1, 8.44e-2, 6.27e-2, 4.56e-2, 3.42e-2, 3.23e-2, 2.35e-2, 2.46e-2]
        v = [4.0, 2.0, 1.0, 5.0e-1, 2.5e-1, 1.67e-1, 1.25e-1, 1.0e-1, 8.33e-2, 7.14e-2, 6.25e-2]

        for i in range(11):
            g_tmp_x_00031 = g_x[1]
            tmp_x_00031 = x[1]
            g_tmp_dfovec_1d_00041 = g_tmp_x_00031
            tmp_dfovec_1d_00041 = v[i] + tmp_x_00031
            g_tmp1 = v[i] * g_tmp_dfovec_1d_00041
            tmp1 = v[i] * tmp_dfovec_1d_00041
            g_tmp_x_00032 = g_x[2]
            tmp_x_00032 = x[2]
            g_tmp_dfovec_1d_00042 = g_tmp_x_00032
            tmp_dfovec_1d_00042 = v[i] + tmp_x_00032
            g_tmp_dfovec_1d_00043 = v[i] * g_tmp_dfovec_1d_00042
            tmp_dfovec_1d_00043 = v[i] * tmp_dfovec_1d_00042
            g_tmp_x_00033 = g_x[3]
            tmp_x_00033 = x[3]
            g_tmp2 = g_tmp_dfovec_1d_00043 + g_tmp_x_00033
            tmp2 = tmp_dfovec_1d_00043 + tmp_x_00033
            g_tmp_x_00034 = g_x[0]
            tmp_x_00034 = x[0]
            g_tmp_dfovec_1d_00044 = g_tmp_x_00034 * tmp1 + tmp_x_00034 * g_tmp1
            tmp_dfovec_1d_00044 = tmp_x_00034 * tmp1
            tmp_dfovec_1d_00045 = tmp_dfovec_1d_00044 / tmp2

            g_tmp_dfovec_1d_00045 = (g_tmp_dfovec_1d_00044.T - np.dot(g_tmp2, tmp_dfovec_1d_00045)) / tmp2

            g_fvec[i] = -g_tmp_dfovec_1d_00045
            fvec[i] = y2[i] - tmp_dfovec_1d_00045

    elif nprob == 10:
        y3 = [3.478e4, 2.861e4, 2.365e4, 1.963e4, 1.637e4, 1.372e4, 1.154e4, 9.744e3, 8.261e3, 7.03e3, 6.005e3, 5.147e3, 4.427e3, 3.82e3, 3.307e3, 2.872e3]
        c45 = 4.5e1

        for i in range(16):
            tmp_dfovec_1d_00046 = 5 * (i + 1)
            g_tmp_x_00035 = g_x[2]
            tmp_x_00035 = x[2]
            g_temp = g_tmp_x_00035
            temp = tmp_dfovec_1d_00046 + c45 + tmp_x_00035
            g_tmp_x_00036 = g_x[1]
            tmp_x_00036 = x[1]
            tmp1 = tmp_x_00036 / temp
            g_tmp1 = (g_tmp_x_00036 - g_temp * tmp1) / temp
            g_tmp2 = g_tmp1 * np.exp(tmp1)
            tmp2 = np.exp(tmp1)
            g_tmp_x_00037 = g_x[0]
            tmp_x_00037 = x[0]
            g_tmp_dfovec_1d_00047 = g_tmp_x_00037 * tmp2 + tmp_x_00037 * g_tmp2
            tmp_dfovec_1d_00047 = tmp_x_00037 * tmp2
            g_fvec[i] = g_tmp_dfovec_1d_00047
            fvec[i] = tmp_dfovec_1d_00047 - y3[i]

    elif nprob == 11:
        c29 = 2.9e1
        for i in range(29):
            div = (i + 1) / c29
            s1 = 0
            g_s1 = np.zeros_like(s1)
            dx = 1
            for j in range(1, n):
                tmp_dfovec_1d_00048 = j
                g_tmp_x_00038 = g_x[j]
                tmp_x_00038 = x[j]
                g_tmp_dfovec_1d_00049 = tmp_dfovec_1d_00048 * dx * g_tmp_x_00038
                tmp_dfovec_1d_00049 = tmp_dfovec_1d_00048 * dx * tmp_x_00038
                g_tmp_dfovec_1d_00194 = g_s1 + g_tmp_dfovec_1d_00049
                tmp_dfovec_1d_00194 = s1 + tmp_dfovec_1d_00049
                g_s1 = g_tmp_dfovec_1d_00194
                s1 = tmp_dfovec_1d_00194
                tmp_dfovec_1d_00195 = div * dx
                dx = tmp_dfovec_1d_00195

            s2 = 0
            g_s2 = np.zeros_like(s2)
            dx = 1
            for j in range(n):
                g_tmp_x_00039 = g_x[j]
                tmp_x_00039 = x[j]
                g_tmp_dfovec_1d_00050 = dx * g_tmp_x_00039
                tmp_dfovec_1d_00050 = dx * tmp_x_00039
                g_tmp_dfovec_1d_00196 = g_s2 + g_tmp_dfovec_1d_00050
                tmp_dfovec_1d_00196 = s2 + tmp_dfovec_1d_00050
                g_s2 = g_tmp_dfovec_1d_00196
                s2 = tmp_dfovec_1d_00196
                tmp_dfovec_1d_00197 = div * dx
                dx = tmp_dfovec_1d_00197

            g_tmp_dfovec_1d_00051 = adimat_g_pow_left(g_s2, s2, 2)[0]
            tmp_dfovec_1d_00051 = s2**2
            g_fvec[i] = g_s1 - g_tmp_dfovec_1d_00051
            fvec[i] = s1 - tmp_dfovec_1d_00051 - 1

        g_tmp_x_00040 = g_x[0]
        tmp_x_00040 = x[0]
        g_fvec[29] = g_tmp_x_00040
        fvec[29] = tmp_x_00040

        g_tmp_x_00041 = g_x[1]
        tmp_x_00041 = x[1]
        g_tmp_x_00042 = g_x[0]
        tmp_x_00042 = x[0]
        g_tmp_dfovec_1d_00052 = adimat_g_pow_left(g_tmp_x_00042, tmp_x_00042, 2)[0]
        tmp_dfovec_1d_00052 = tmp_x_00042**2
        g_fvec[30] = g_tmp_x_00041 - g_tmp_dfovec_1d_00052
        fvec[30] = tmp_x_00041 - tmp_dfovec_1d_00052 - 1

    elif nprob == 12:
        for i in range(m):
            temp = i + 1
            g_temp = np.zeros_like(temp)
            g_tmp1 = g_temp / 10
            tmp1 = temp / 10
            g_tmp_dfovec_1d_00053 = -g_tmp1
            tmp_dfovec_1d_00053 = -tmp1
            g_tmp_x_00043 = g_x[0]
            tmp_x_00043 = x[0]
            g_tmp_dfovec_1d_00054 = g_tmp_dfovec_1d_00053 * tmp_x_00043 + tmp_dfovec_1d_00053 * g_tmp_x_00043
            tmp_dfovec_1d_00054 = tmp_dfovec_1d_00053 * tmp_x_00043
            g_tmp_exp_00000 = g_tmp_dfovec_1d_00054 * np.exp(tmp_dfovec_1d_00054)
            tmp_exp_00000 = np.exp(tmp_dfovec_1d_00054)
            g_tmp_x_00044 = g_x[1]
            tmp_x_00044 = x[1]
            g_tmp_dfovec_1d_00055 = g_tmp_dfovec_1d_00053 * tmp_x_00044 + tmp_dfovec_1d_00053 * g_tmp_x_00044
            tmp_dfovec_1d_00055 = tmp_dfovec_1d_00053 * tmp_x_00044
            g_tmp_exp_00001 = g_tmp_dfovec_1d_00055 * np.exp(tmp_dfovec_1d_00055)
            tmp_exp_00001 = np.exp(tmp_dfovec_1d_00055)
            g_tmp_dfovec_1d_00056 = -g_temp
            tmp_dfovec_1d_00056 = -temp
            g_tmp_exp_00002 = g_tmp_dfovec_1d_00056 * np.exp(tmp_dfovec_1d_00056)
            tmp_exp_00002 = np.exp(tmp_dfovec_1d_00056)
            g_tmp_exp_00003 = g_tmp_dfovec_1d_00053 * np.exp(tmp_dfovec_1d_00053)
            tmp_exp_00003 = np.exp(tmp_dfovec_1d_00053)
            g_tmp_dfovec_1d_00057 = g_tmp_exp_00002 - g_tmp_exp_00003
            tmp_dfovec_1d_00057 = tmp_exp_00002 - tmp_exp_00003
            g_tmp_x_00045 = g_x[2]
            tmp_x_00045 = x[2]
            g_tmp_dfovec_1d_00058 = g_tmp_dfovec_1d_00057 * tmp_x_00045 + tmp_dfovec_1d_00057 * g_tmp_x_00045
            tmp_dfovec_1d_00058 = tmp_dfovec_1d_00057 * tmp_x_00045
            g_fvec[i] = g_tmp_exp_00000 - g_tmp_exp_00001 + g_tmp_dfovec_1d_00058
            fvec[i] = tmp_exp_00000 - tmp_exp_00001 + tmp_dfovec_1d_00058
    elif nprob == 13:
        for i in range(m):
            temp = i + 1
            g_temp = np.zeros(1)
            g_tmp_dfovec_1d_00059 = 2 * g_temp
            tmp_dfovec_1d_00059 = 2 * temp
            g_tmp_x_00046 = g_x[0]
            tmp_x_00046 = x[0]
            g_tmp_dfovec_1d_00060 = g_temp * tmp_x_00046 + temp * g_tmp_x_00046
            tmp_dfovec_1d_00060 = temp * tmp_x_00046
            g_tmp_exp_00004 = g_tmp_dfovec_1d_00060 * np.exp(tmp_dfovec_1d_00060)
            tmp_exp_00004 = np.exp(tmp_dfovec_1d_00060)
            g_tmp_x_00047 = g_x[1]
            tmp_x_00047 = x[1]
            g_tmp_dfovec_1d_00061 = g_temp * tmp_x_00047 + temp * g_tmp_x_00047
            tmp_dfovec_1d_00061 = temp * tmp_x_00047
            g_tmp_exp_00005 = g_tmp_dfovec_1d_00061 * np.exp(tmp_dfovec_1d_00061)
            tmp_exp_00005 = np.exp(tmp_dfovec_1d_00061)
            g_fvec[i] = g_tmp_dfovec_1d_00059 - g_tmp_exp_00004 - g_tmp_exp_00005
            fvec[i] = 2 + tmp_dfovec_1d_00059 - tmp_exp_00004 - tmp_exp_00005
    elif nprob == 14:
        for i in range(m):
            temp = (i + 1) / 5.0
            g_temp = np.zeros(1)
            g_tmp_x_00048 = g_x[0]
            tmp_x_00048 = x[0]
            g_tmp_x_00049 = g_x[1]
            tmp_x_00049 = x[1]
            g_tmp_dfovec_1d_00062 = g_temp * tmp_x_00049 + temp * g_tmp_x_00049
            tmp_dfovec_1d_00062 = temp * tmp_x_00049
            g_tmp_exp_00006 = g_temp * np.exp(temp)
            tmp_exp_00006 = np.exp(temp)
            g_tmp1 = g_tmp_x_00048 + g_tmp_dfovec_1d_00062 - g_tmp_exp_00006
            tmp1 = tmp_x_00048 + tmp_dfovec_1d_00062 - tmp_exp_00006
            g_tmp_x_00050 = g_x[2]
            tmp_x_00050 = x[2]
            g_tmp_sin_00000 = g_temp * np.cos(temp)
            tmp_sin_00000 = np.sin(temp)
            g_tmp_x_00051 = g_x[3]
            tmp_x_00051 = x[3]
            g_tmp_dfovec_1d_00063 = g_tmp_sin_00000 * tmp_x_00051 + tmp_sin_00000 * g_tmp_x_00051
            tmp_dfovec_1d_00063 = tmp_sin_00000 * tmp_x_00051
            g_tmp_cos_00000 = g_temp * (-np.sin(temp))
            tmp_cos_00000 = np.cos(temp)
            g_tmp2 = g_tmp_x_00050 + g_tmp_dfovec_1d_00063 - g_tmp_cos_00000
            tmp2 = tmp_x_00050 + tmp_dfovec_1d_00063 - tmp_cos_00000
            g_tmp_dfovec_1d_00064 = adimat_g_pow_left(g_tmp1, tmp1, 2)[0]
            tmp_dfovec_1d_00064 = tmp1**2
            g_tmp_dfovec_1d_00065 = adimat_g_pow_left(g_tmp2, tmp2, 2)[0]
            tmp_dfovec_1d_00065 = tmp2**2
            g_fvec[i] = g_tmp_dfovec_1d_00064 + g_tmp_dfovec_1d_00065
            fvec[i] = tmp_dfovec_1d_00064 + tmp_dfovec_1d_00065

    elif nprob == 15:
        for j in range(n):
            t1 = 1
            g_t1 = np.zeros_like(t1)
            g_tmp_x_00052 = g_x[j]
            tmp_x_00052 = x[j]
            g_tmp_dfovec_1d_00066 = 2 * g_tmp_x_00052
            tmp_dfovec_1d_00066 = 2 * tmp_x_00052
            g_t2 = g_tmp_dfovec_1d_00066
            t2 = tmp_dfovec_1d_00066 - 1
            g_t = 2 * g_t2
            t = 2 * t2
            for i in range(m):
                g_tmp_fvec_00001 = g_fvec[i]
                tmp_fvec_00001 = fvec[i]
                g_fvec[i] = g_tmp_fvec_00001 + g_t2
                fvec[i] = tmp_fvec_00001 + t2
                g_tmp_dfovec_1d_00067 = g_t * t2 + t * g_t2
                tmp_dfovec_1d_00067 = t * t2
                g_th = g_tmp_dfovec_1d_00067 - g_t1
                th = tmp_dfovec_1d_00067 - t1
                g_t1 = g_t2
                t1 = t2
                g_t2 = g_th
                t2 = th
        iev = -1
        for i in range(m):
            g_tmp_fvec_00002 = g_fvec[i]
            tmp_fvec_00002 = fvec[i]
            g_fvec[i] = (g_tmp_fvec_00002 / n).T
            fvec[i] = tmp_fvec_00002 / n
            if iev > 0:
                g_tmp_fvec_00003 = g_fvec[i]
                tmp_fvec_00003 = fvec[i]
                tmp_dfovec_1d_00068 = (i + 1) ** 2
                tmp_dfovec_1d_00069 = tmp_dfovec_1d_00068 - 1
                tmp_dfovec_1d_00070 = 1 / tmp_dfovec_1d_00069
                g_fvec[i] = g_tmp_fvec_00003
                fvec[i] = tmp_fvec_00003 + tmp_dfovec_1d_00070
            tmp_dfovec_1d_00198 = -iev
            iev = tmp_dfovec_1d_00198

    elif nprob == 16:
        tmp_dfovec_1d_00071 = n + 1
        sum1 = -tmp_dfovec_1d_00071
        g_sum1 = np.zeros_like(sum1)
        prod1 = 1
        g_prod1 = np.zeros_like(prod1)
        for j in range(n):
            g_tmp_x_00053 = g_x[j]
            tmp_x_00053 = x[j]
            g_tmp_dfovec_1d_00199 = g_sum1 + g_tmp_x_00053
            tmp_dfovec_1d_00199 = sum1 + tmp_x_00053
            g_sum1 = g_tmp_dfovec_1d_00199
            sum1 = tmp_dfovec_1d_00199
            g_tmp_x_00054 = g_x[j]
            tmp_x_00054 = x[j]
            g_tmp_dfovec_1d_00200 = g_tmp_x_00054 * prod1 + tmp_x_00054 * g_prod1
            tmp_dfovec_1d_00200 = tmp_x_00054 * prod1
            g_prod1 = g_tmp_dfovec_1d_00200
            prod1 = tmp_dfovec_1d_00200
        tmp_dfovec_1d_00072 = n - 1
        for i in range(tmp_dfovec_1d_00072):
            g_tmp_x_00055 = g_x[i]
            tmp_x_00055 = x[i]
            g_fvec[i] = g_tmp_x_00055 + g_sum1
            fvec[i] = tmp_x_00055 + sum1
            tmp_dfovec_1d_00072 = n - 1
        g_fvec[n - 1] = g_prod1
        fvec[n - 1] = prod1 - 1
    elif nprob == 17:
        y4 = [
            8.44e-1,
            9.08e-1,
            9.32e-1,
            9.36e-1,
            9.25e-1,
            9.08e-1,
            8.81e-1,
            8.5e-1,
            8.18e-1,
            7.84e-1,
            7.51e-1,
            7.18e-1,
            6.85e-1,
            6.58e-1,
            6.28e-1,
            6.03e-1,
            5.8e-1,
            5.58e-1,
            5.38e-1,
            5.22e-1,
            5.06e-1,
            4.9e-1,
            4.78e-1,
            4.67e-1,
            4.57e-1,
            4.48e-1,
            4.38e-1,
            4.31e-1,
            4.24e-1,
            4.2e-1,
            4.14e-1,
            4.11e-1,
            4.06e-1,
        ]
        for i in range(33):
            tmp_dfovec_1d_00073 = i
            temp = 10 * tmp_dfovec_1d_00073
            g_temp = 0.0

            g_tmp_x_00056 = g_x[3]
            tmp_x_00056 = x[3]
            g_tmp_dfovec_1d_00074 = -g_tmp_x_00056
            tmp_dfovec_1d_00074 = -tmp_x_00056
            g_tmp_dfovec_1d_00075 = g_tmp_dfovec_1d_00074 * temp + tmp_dfovec_1d_00074 * g_temp
            tmp_dfovec_1d_00075 = tmp_dfovec_1d_00074 * temp
            g_tmp1 = g_tmp_dfovec_1d_00075 * np.exp(tmp_dfovec_1d_00075)
            tmp1 = np.exp(tmp_dfovec_1d_00075)

            g_tmp_x_00057 = g_x[4]
            tmp_x_00057 = x[4]
            g_tmp_dfovec_1d_00076 = -g_tmp_x_00057
            tmp_dfovec_1d_00076 = -tmp_x_00057
            g_tmp_dfovec_1d_00077 = g_tmp_dfovec_1d_00076 * temp + tmp_dfovec_1d_00076 * g_temp
            tmp_dfovec_1d_00077 = tmp_dfovec_1d_00076 * temp
            g_tmp2 = g_tmp_dfovec_1d_00077 * np.exp(tmp_dfovec_1d_00077)
            tmp2 = np.exp(tmp_dfovec_1d_00077)

            g_tmp_x_00058 = g_x[0]
            tmp_x_00058 = x[0]
            g_tmp_x_00059 = g_x[1]
            tmp_x_00059 = x[1]
            g_tmp_dfovec_1d_00078 = g_tmp_x_00059 * tmp1 + tmp_x_00059 * g_tmp1
            tmp_dfovec_1d_00078 = tmp_x_00059 * tmp1
            g_tmp_x_00060 = g_x[2]
            tmp_x_00060 = x[2]
            g_tmp_dfovec_1d_00079 = g_tmp_x_00060 * tmp2 + tmp_x_00060 * g_tmp2
            tmp_dfovec_1d_00079 = tmp_x_00060 * tmp2
            g_tmp_dfovec_1d_00080 = g_tmp_x_00058 + g_tmp_dfovec_1d_00078 + g_tmp_dfovec_1d_00079
            tmp_dfovec_1d_00080 = tmp_x_00058 + tmp_dfovec_1d_00078 + tmp_dfovec_1d_00079
            g_fvec[i] = -g_tmp_dfovec_1d_00080
            fvec[i] = y4[i] - tmp_dfovec_1d_00080

    elif nprob == 18:
        y5 = [
            1.366,
            1.191,
            1.112,
            1.013,
            9.91e-1,
            8.85e-1,
            8.31e-1,
            8.47e-1,
            7.86e-1,
            7.25e-1,
            7.46e-1,
            6.79e-1,
            6.08e-1,
            6.55e-1,
            6.16e-1,
            6.06e-1,
            6.02e-1,
            6.26e-1,
            6.51e-1,
            7.24e-1,
            6.49e-1,
            6.49e-1,
            6.94e-1,
            6.44e-1,
            6.24e-1,
            6.61e-1,
            6.12e-1,
            5.58e-1,
            5.33e-1,
            4.95e-1,
            5.0e-1,
            4.23e-1,
            3.95e-1,
            3.75e-1,
            3.72e-1,
            3.91e-1,
            3.96e-1,
            4.05e-1,
            4.28e-1,
            4.29e-1,
            5.23e-1,
            5.62e-1,
            6.07e-1,
            6.53e-1,
            6.72e-1,
            7.08e-1,
            6.33e-1,
            6.68e-1,
            6.45e-1,
            6.32e-1,
            5.91e-1,
            5.59e-1,
            5.97e-1,
            6.25e-1,
            7.39e-1,
            7.1e-1,
            7.29e-1,
            7.2e-1,
            6.36e-1,
            5.81e-1,
            4.28e-1,
            2.92e-1,
            1.62e-1,
            9.8e-2,
            5.4e-2,
        ]
        for i in range(65):
            tmp_dfovec_1d_00081 = i
            temp = tmp_dfovec_1d_00081 / 10.0
            g_temp = 0.0

            g_tmp_x_00061 = g_x[4]
            tmp_x_00061 = x[4]
            g_tmp_dfovec_1d_00082 = -g_tmp_x_00061
            tmp_dfovec_1d_00082 = -tmp_x_00061
            g_tmp_dfovec_1d_00083 = g_tmp_dfovec_1d_00082 * temp + tmp_dfovec_1d_00082 * g_temp
            tmp_dfovec_1d_00083 = tmp_dfovec_1d_00082 * temp
            g_tmp1 = g_tmp_dfovec_1d_00083 * np.exp(tmp_dfovec_1d_00083)
            tmp1 = np.exp(tmp_dfovec_1d_00083)

            g_tmp_x_00062 = g_x[5]
            tmp_x_00062 = x[5]
            g_tmp_dfovec_1d_00084 = -g_tmp_x_00062
            tmp_dfovec_1d_00084 = -tmp_x_00062

            g_tmp_x_00063 = g_x[8]
            tmp_x_00063 = x[8]
            g_tmp_dfovec_1d_00085 = g_temp - g_tmp_x_00063
            tmp_dfovec_1d_00085 = temp - tmp_x_00063
            g_tmp_dfovec_1d_00086 = adimat_g_pow_left(g_tmp_dfovec_1d_00085, tmp_dfovec_1d_00085, 2)[0]
            tmp_dfovec_1d_00086 = tmp_dfovec_1d_00085**2
            g_tmp_dfovec_1d_00087 = g_tmp_dfovec_1d_00084 * tmp_dfovec_1d_00086 + tmp_dfovec_1d_00084 * g_tmp_dfovec_1d_00086
            tmp_dfovec_1d_00087 = tmp_dfovec_1d_00084 * tmp_dfovec_1d_00086
            g_tmp2 = g_tmp_dfovec_1d_00087 * np.exp(tmp_dfovec_1d_00087)
            tmp2 = np.exp(tmp_dfovec_1d_00087)

            g_tmp_x_00064 = g_x[6]
            tmp_x_00064 = x[6]
            g_tmp_dfovec_1d_00088 = -g_tmp_x_00064
            tmp_dfovec_1d_00088 = -tmp_x_00064

            g_tmp_x_00065 = g_x[9]
            tmp_x_00065 = x[9]
            g_tmp_dfovec_1d_00089 = g_temp - g_tmp_x_00065
            tmp_dfovec_1d_00089 = temp - tmp_x_00065
            g_tmp_dfovec_1d_00090 = adimat_g_pow_left(g_tmp_dfovec_1d_00089, tmp_dfovec_1d_00089, 2)[0]
            tmp_dfovec_1d_00090 = tmp_dfovec_1d_00089**2
            g_tmp_dfovec_1d_00091 = g_tmp_dfovec_1d_00088 * tmp_dfovec_1d_00090 + tmp_dfovec_1d_00088 * g_tmp_dfovec_1d_00090
            tmp_dfovec_1d_00091 = tmp_dfovec_1d_00088 * tmp_dfovec_1d_00090
            g_tmp3 = g_tmp_dfovec_1d_00091 * np.exp(tmp_dfovec_1d_00091)
            tmp3 = np.exp(tmp_dfovec_1d_00091)

            g_tmp_x_00066 = g_x[7]
            tmp_x_00066 = x[7]
            g_tmp_dfovec_1d_00092 = -g_tmp_x_00066
            tmp_dfovec_1d_00092 = -tmp_x_00066

            g_tmp_x_00067 = g_x[10]
            tmp_x_00067 = x[10]
            g_tmp_dfovec_1d_00093 = g_temp - g_tmp_x_00067
            tmp_dfovec_1d_00093 = temp - tmp_x_00067
            g_tmp_dfovec_1d_00094 = adimat_g_pow_left(g_tmp_dfovec_1d_00093, tmp_dfovec_1d_00093, 2)[0]
            tmp_dfovec_1d_00094 = tmp_dfovec_1d_00093**2
            g_tmp_dfovec_1d_00095 = g_tmp_dfovec_1d_00092 * tmp_dfovec_1d_00094 + tmp_dfovec_1d_00092 * g_tmp_dfovec_1d_00094
            tmp_dfovec_1d_00095 = tmp_dfovec_1d_00092 * tmp_dfovec_1d_00094
            g_tmp4 = g_tmp_dfovec_1d_00095 * np.exp(tmp_dfovec_1d_00095)
            tmp4 = np.exp(tmp_dfovec_1d_00095)

            g_tmp_x_00068 = g_x[0]
            tmp_x_00068 = x[0]
            g_tmp_dfovec_1d_00096 = g_tmp_x_00068 * tmp1 + tmp_x_00068 * g_tmp1
            tmp_dfovec_1d_00096 = tmp_x_00068 * tmp1
            g_tmp_x_00069 = g_x[1]
            tmp_x_00069 = x[1]
            g_tmp_dfovec_1d_00097 = g_tmp_x_00069 * tmp2 + tmp_x_00069 * g_tmp2
            tmp_dfovec_1d_00097 = tmp_x_00069 * tmp2
            g_tmp_x_00070 = g_x[2]
            tmp_x_00070 = x[2]
            g_tmp_dfovec_1d_00098 = g_tmp_x_00070 * tmp3 + tmp_x_00070 * g_tmp3
            tmp_dfovec_1d_00098 = tmp_x_00070 * tmp3
            g_tmp_x_00071 = g_x[3]
            tmp_x_00071 = x[3]
            g_tmp_dfovec_1d_00099 = g_tmp_x_00071 * tmp4 + tmp_x_00071 * g_tmp4
            tmp_dfovec_1d_00099 = tmp_x_00071 * tmp4
            g_tmp_dfovec_1d_00100 = g_tmp_dfovec_1d_00096 + g_tmp_dfovec_1d_00097 + g_tmp_dfovec_1d_00098 + g_tmp_dfovec_1d_00099
            tmp_dfovec_1d_00100 = tmp_dfovec_1d_00096 + tmp_dfovec_1d_00097 + tmp_dfovec_1d_00098 + tmp_dfovec_1d_00099
            g_fvec[i] = -g_tmp_dfovec_1d_00100
            fvec[i] = y5[i] - tmp_dfovec_1d_00100
    elif nprob == 19:
        tmp_dfovec_1d_00101 = n - 4
        for i in range(tmp_dfovec_1d_00101):
            g_tmp_x_00072 = g_x[i]
            tmp_x_00072 = x[i]
            g_tmp_dfovec_1d_00102 = -4 * g_tmp_x_00072
            tmp_dfovec_1d_00102 = -4 * tmp_x_00072
            g_tmp_dfovec_1d_00103 = g_tmp_dfovec_1d_00102
            tmp_dfovec_1d_00103 = tmp_dfovec_1d_00102 + 3.0
            g_fvec[i] = g_tmp_dfovec_1d_00103
            fvec[i] = tmp_dfovec_1d_00103

            g_tmp_x_00073 = g_x[i]
            tmp_x_00073 = x[i]
            g_tmp_dfovec_1d_00104 = adimat_g_pow_left(g_tmp_x_00073, tmp_x_00073, 2)[0]
            tmp_dfovec_1d_00104 = tmp_x_00073**2
            tmp_dfovec_1d_00105 = i + 1

            g_tmp_x_00074 = g_x[tmp_dfovec_1d_00105]
            tmp_x_00074 = x[tmp_dfovec_1d_00105]
            g_tmp_dfovec_1d_00106 = adimat_g_pow_left(g_tmp_x_00074, tmp_x_00074, 2)[0]
            tmp_dfovec_1d_00106 = tmp_x_00074**2

            g_tmp_dfovec_1d_00107 = 2 * g_tmp_dfovec_1d_00106
            tmp_dfovec_1d_00107 = 2 * tmp_dfovec_1d_00106
            tmp_dfovec_1d_00108 = i + 2

            g_tmp_x_00075 = g_x[tmp_dfovec_1d_00108]
            tmp_x_00075 = x[tmp_dfovec_1d_00108]
            g_tmp_dfovec_1d_00109 = adimat_g_pow_left(g_tmp_x_00075, tmp_x_00075, 2)[0]
            tmp_dfovec_1d_00109 = tmp_x_00075**2

            g_tmp_dfovec_1d_00110 = 3 * g_tmp_dfovec_1d_00109
            tmp_dfovec_1d_00110 = 3 * tmp_dfovec_1d_00109
            tmp_dfovec_1d_00111 = i + 3

            g_tmp_x_00076 = g_x[tmp_dfovec_1d_00111]
            tmp_x_00076 = x[tmp_dfovec_1d_00111]
            g_tmp_dfovec_1d_00112 = adimat_g_pow_left(g_tmp_x_00076, tmp_x_00076, 2)[0]
            tmp_dfovec_1d_00112 = tmp_x_00076**2

            g_tmp_dfovec_1d_00113 = 4 * g_tmp_dfovec_1d_00112
            tmp_dfovec_1d_00113 = 4 * tmp_dfovec_1d_00112

            g_tmp_x_00077 = g_x[n - 1]
            tmp_x_00077 = x[n - 1]
            g_tmp_dfovec_1d_00114 = adimat_g_pow_left(g_tmp_x_00077, tmp_x_00077, 2)[0]
            tmp_dfovec_1d_00114 = tmp_x_00077**2

            g_tmp_dfovec_1d_00115 = 5 * g_tmp_dfovec_1d_00114
            tmp_dfovec_1d_00115 = 5 * tmp_dfovec_1d_00114

            g_tmp_dfovec_1d_00116 = g_tmp_dfovec_1d_00104 + g_tmp_dfovec_1d_00107 + g_tmp_dfovec_1d_00110 + g_tmp_dfovec_1d_00113 + g_tmp_dfovec_1d_00115
            tmp_dfovec_1d_00116 = tmp_dfovec_1d_00104 + tmp_dfovec_1d_00107 + tmp_dfovec_1d_00110 + tmp_dfovec_1d_00113 + tmp_dfovec_1d_00115

            g_fvec[n - 4 + i] = g_tmp_dfovec_1d_00116
            fvec[n - 4 + i] = tmp_dfovec_1d_00116

    elif nprob == 20:
        g_tmp_x_00078 = g_x[0]
        tmp_x_00078 = x[0]
        g_tmp_dfovec_1d_00117 = g_tmp_x_00078
        tmp_dfovec_1d_00117 = tmp_x_00078 - 1.0
        g_fvec[0] = g_tmp_dfovec_1d_00117
        fvec[0] = tmp_dfovec_1d_00117

        for i in range(1, n):
            g_tmp_x_00079 = g_x[i]
            tmp_x_00079 = x[i]
            tmp_dfovec_1d_00118 = i - 1

            g_tmp_x_00080 = g_x[tmp_dfovec_1d_00118]
            tmp_x_00080 = x[tmp_dfovec_1d_00118]
            g_tmp_dfovec_1d_00119 = adimat_g_pow_left(g_tmp_x_00080, tmp_x_00080, 3)[0]
            tmp_dfovec_1d_00119 = tmp_x_00080**3

            g_tmp_dfovec_1d_00120 = g_tmp_x_00079 - g_tmp_dfovec_1d_00119
            tmp_dfovec_1d_00120 = tmp_x_00079 - tmp_dfovec_1d_00119

            g_fvec[i] = 10 * g_tmp_dfovec_1d_00120
            fvec[i] = 10 * tmp_dfovec_1d_00120

    elif nprob == 21:
        for i in range(n):
            ss = 0
            g_ss = np.zeros_like(ss)
            for j in range(n):
                g_tmp_x_00081 = g_x[i]
                tmp_x_00081 = x[i]
                g_tmp_dfovec_1d_00121 = adimat_g_pow_left(g_tmp_x_00081, tmp_x_00081, 2)[0]
                tmp_dfovec_1d_00121 = tmp_x_00081**2
                tmp_dfovec_1d_00122 = (i + 1) / (j + 1)

                g_tmp_dfovec_1d_00123 = g_tmp_dfovec_1d_00121
                tmp_dfovec_1d_00123 = tmp_dfovec_1d_00121 + tmp_dfovec_1d_00122

                v2 = np.sqrt(tmp_dfovec_1d_00123)
                g_v2 = g_tmp_dfovec_1d_00123 / (2 * v2)

                g_tmp_log_00000 = g_v2 / v2
                tmp_log_00000 = np.log(v2)
                g_tmp_sin_00001 = g_tmp_log_00000 * np.cos(tmp_log_00000)
                tmp_sin_00001 = np.sin(tmp_log_00000)

                g_tmp_dfovec_1d_00124 = adimat_g_pow_left(g_tmp_sin_00001, tmp_sin_00001, 5)[0]
                tmp_dfovec_1d_00124 = tmp_sin_00001**5

                g_tmp_cos_00001 = g_tmp_log_00000 * (-np.sin(tmp_log_00000))
                tmp_cos_00001 = np.cos(tmp_log_00000)

                g_tmp_dfovec_1d_00125 = adimat_g_pow_left(g_tmp_cos_00001, tmp_cos_00001, 5)[0]
                tmp_dfovec_1d_00125 = tmp_cos_00001**5

                g_tmp_dfovec_1d_00126 = g_tmp_dfovec_1d_00124 + g_tmp_dfovec_1d_00125
                tmp_dfovec_1d_00126 = tmp_dfovec_1d_00124 + tmp_dfovec_1d_00125

                g_tmp_dfovec_1d_00127 = g_v2 * tmp_dfovec_1d_00126 + v2 * g_tmp_dfovec_1d_00126
                tmp_dfovec_1d_00127 = v2 * tmp_dfovec_1d_00126

                g_tmp_dfovec_1d_00201 = g_ss + g_tmp_dfovec_1d_00127
                tmp_dfovec_1d_00201 = ss + tmp_dfovec_1d_00127

                g_ss = g_tmp_dfovec_1d_00201
                ss = tmp_dfovec_1d_00201

            g_tmp_x_00082 = g_x[i]
            tmp_x_00082 = x[i]
            g_tmp_dfovec_1d_00128 = 1400 * g_tmp_x_00082
            tmp_dfovec_1d_00128 = 1400 * tmp_x_00082
            tmp_dfovec_1d_00129 = i - 50 + 1
            tmp_dfovec_1d_00130 = tmp_dfovec_1d_00129**3
            g_fvec[i] = g_tmp_dfovec_1d_00128 + g_ss
            fvec[i] = tmp_dfovec_1d_00128 + tmp_dfovec_1d_00130 + ss
    elif nprob == 22:  # m=n=8
        g_tmp_x_00083 = g_x[0]
        tmp_x_00083 = x[0]
        g_tmp_x_00084 = g_x[1]
        tmp_x_00084 = x[1]
        g_fvec[0] = g_tmp_x_00083 + g_tmp_x_00084
        fvec[0] = tmp_x_00083 + tmp_x_00084 + 0.69
        g_tmp_x_00085 = g_x[2]
        tmp_x_00085 = x[2]
        g_tmp_x_00086 = g_x[3]
        tmp_x_00086 = x[3]
        g_fvec[1] = g_tmp_x_00085 + g_tmp_x_00086
        fvec[1] = tmp_x_00085 + tmp_x_00086 + 0.044
        g_tmp_x_00087 = g_x[4]
        tmp_x_00087 = x[4]
        g_tmp_x_00088 = g_x[0]
        tmp_x_00088 = x[0]
        g_tmp_dfovec_1d_00131 = g_tmp_x_00087 * tmp_x_00088 + tmp_x_00087 * g_tmp_x_00088
        tmp_dfovec_1d_00131 = tmp_x_00087 * tmp_x_00088
        g_tmp_x_00089 = g_x[5]
        tmp_x_00089 = x[5]
        g_tmp_x_00090 = g_x[1]
        tmp_x_00090 = x[1]
        g_tmp_dfovec_1d_00132 = g_tmp_x_00089 * tmp_x_00090 + tmp_x_00089 * g_tmp_x_00090
        tmp_dfovec_1d_00132 = tmp_x_00089 * tmp_x_00090
        g_tmp_x_00091 = g_x[6]
        tmp_x_00091 = x[6]
        g_tmp_x_00092 = g_x[2]
        tmp_x_00092 = x[2]
        g_tmp_dfovec_1d_00133 = g_tmp_x_00091 * tmp_x_00092 + tmp_x_00091 * g_tmp_x_00092
        tmp_dfovec_1d_00133 = tmp_x_00091 * tmp_x_00092
        g_tmp_x_00093 = g_x[7]
        tmp_x_00093 = x[7]
        g_tmp_x_00094 = g_x[3]
        tmp_x_00094 = x[3]
        g_tmp_dfovec_1d_00134 = g_tmp_x_00093 * tmp_x_00094 + tmp_x_00093 * g_tmp_x_00094
        tmp_dfovec_1d_00134 = tmp_x_00093 * tmp_x_00094
        g_fvec[2] = g_tmp_dfovec_1d_00131 + g_tmp_dfovec_1d_00132 - g_tmp_dfovec_1d_00133 - g_tmp_dfovec_1d_00134
        fvec[2] = tmp_dfovec_1d_00131 + tmp_dfovec_1d_00132 - tmp_dfovec_1d_00133 - tmp_dfovec_1d_00134 + 1.57
        g_tmp_x_00095 = g_x[6]
        tmp_x_00095 = x[6]
        g_tmp_x_00096 = g_x[0]
        tmp_x_00096 = x[0]
        g_tmp_dfovec_1d_00135 = g_tmp_x_00095 * tmp_x_00096 + tmp_x_00095 * g_tmp_x_00096
        tmp_dfovec_1d_00135 = tmp_x_00095 * tmp_x_00096
        g_tmp_x_00097 = g_x[7]
        tmp_x_00097 = x[7]
        g_tmp_x_00098 = g_x[1]
        tmp_x_00098 = x[1]
        g_tmp_dfovec_1d_00136 = g_tmp_x_00097 * tmp_x_00098 + tmp_x_00097 * g_tmp_x_00098
        tmp_dfovec_1d_00136 = tmp_x_00097 * tmp_x_00098
        g_tmp_x_00099 = g_x[4]
        tmp_x_00099 = x[4]
        g_tmp_x_00100 = g_x[2]
        tmp_x_00100 = x[2]
        g_tmp_dfovec_1d_00137 = g_tmp_x_00099 * tmp_x_00100 + tmp_x_00099 * g_tmp_x_00100
        tmp_dfovec_1d_00137 = tmp_x_00099 * tmp_x_00100
        g_tmp_x_00101 = g_x[5]
        tmp_x_00101 = x[5]
        g_tmp_x_00102 = g_x[3]
        tmp_x_00102 = x[3]
        g_tmp_dfovec_1d_00138 = g_tmp_x_00101 * tmp_x_00102 + tmp_x_00101 * g_tmp_x_00102
        tmp_dfovec_1d_00138 = tmp_x_00101 * tmp_x_00102
        g_fvec[3] = g_tmp_dfovec_1d_00135 + g_tmp_dfovec_1d_00136 + g_tmp_dfovec_1d_00137 + g_tmp_dfovec_1d_00138
        fvec[3] = tmp_dfovec_1d_00135 + tmp_dfovec_1d_00136 + tmp_dfovec_1d_00137 + tmp_dfovec_1d_00138 + 1.31
        g_tmp_x_00103 = g_x[0]
        tmp_x_00103 = x[0]
        g_tmp_x_00104 = g_x[4]
        tmp_x_00104 = x[4]
        g_tmp_dfovec_1d_00139 = adimat_g_pow_left(g_tmp_x_00104, tmp_x_00104, 2)[0]
        tmp_dfovec_1d_00139 = tmp_x_00104**2
        g_tmp_x_00105 = g_x[6]
        tmp_x_00105 = x[6]
        g_tmp_dfovec_1d_00140 = adimat_g_pow_left(g_tmp_x_00105, tmp_x_00105, 2)[0]
        tmp_dfovec_1d_00140 = tmp_x_00105**2
        g_tmp_dfovec_1d_00141 = g_tmp_dfovec_1d_00139 - g_tmp_dfovec_1d_00140
        tmp_dfovec_1d_00141 = tmp_dfovec_1d_00139 - tmp_dfovec_1d_00140
        g_tmp_dfovec_1d_00142 = g_tmp_x_00103 * tmp_dfovec_1d_00141 + tmp_x_00103 * g_tmp_dfovec_1d_00141
        tmp_dfovec_1d_00142 = tmp_x_00103 * tmp_dfovec_1d_00141
        g_tmp_x_00106 = g_x[2]
        tmp_x_00106 = x[2]
        g_tmp_dfovec_1d_00143 = 2.0 * g_tmp_x_00106 * tmp_x_00104 * tmp_x_00105 + 2.0 * tmp_x_00106 * g_tmp_x_00104 * tmp_x_00105 + 2.0 * tmp_x_00106 * tmp_x_00104 * g_tmp_x_00105
        tmp_dfovec_1d_00143 = 2.0 * tmp_x_00106 * tmp_x_00104 * tmp_x_00105
        g_tmp_x_00107 = g_x[1]
        tmp_x_00107 = x[1]
        g_tmp_x_00108 = g_x[5]
        tmp_x_00108 = x[5]
        g_tmp_dfovec_1d_00144 = adimat_g_pow_left(g_tmp_x_00108, tmp_x_00108, 2)[0]
        tmp_dfovec_1d_00144 = tmp_x_00108**2
        g_tmp_x_00109 = g_x[7]
        tmp_x_00109 = x[7]
        g_tmp_dfovec_1d_00145 = adimat_g_pow_left(g_tmp_x_00109, tmp_x_00109, 2)[0]
        tmp_dfovec_1d_00145 = tmp_x_00109**2
        g_tmp_dfovec_1d_00146 = g_tmp_dfovec_1d_00144 - g_tmp_dfovec_1d_00145
        tmp_dfovec_1d_00146 = tmp_dfovec_1d_00144 - tmp_dfovec_1d_00145
        g_tmp_dfovec_1d_00147 = g_tmp_x_00107 * tmp_dfovec_1d_00146 + tmp_x_00107 * g_tmp_dfovec_1d_00146
        tmp_dfovec_1d_00147 = tmp_x_00107 * tmp_dfovec_1d_00146
        g_tmp_x_00110 = g_x[3]
        tmp_x_00110 = x[3]
        g_tmp_dfovec_1d_00148 = 2.0 * g_tmp_x_00110 * tmp_x_00108 * tmp_x_00109 + 2.0 * tmp_x_00110 * g_tmp_x_00108 * tmp_x_00109 + 2.0 * tmp_x_00110 * tmp_x_00108 * g_tmp_x_00109
        tmp_dfovec_1d_00148 = 2.0 * tmp_x_00110 * tmp_x_00108 * tmp_x_00109
        g_fvec[4] = g_tmp_dfovec_1d_00142 - g_tmp_dfovec_1d_00143 + g_tmp_dfovec_1d_00147 - g_tmp_dfovec_1d_00148
        fvec[4] = tmp_dfovec_1d_00142 - tmp_dfovec_1d_00143 + tmp_dfovec_1d_00147 - tmp_dfovec_1d_00148 + 2.65
        g_tmp_x_00111 = g_x[2]
        tmp_x_00111 = x[2]
        g_tmp_x_00112 = g_x[4]
        tmp_x_00112 = x[4]
        g_tmp_dfovec_1d_00149 = adimat_g_pow_left(g_tmp_x_00112, tmp_x_00112, 2)[0]
        tmp_dfovec_1d_00149 = tmp_x_00112**2
        g_tmp_x_00113 = g_x[6]
        tmp_x_00113 = x[6]
        g_tmp_dfovec_1d_00150 = adimat_g_pow_left(g_tmp_x_00113, tmp_x_00113, 2)[0]
        tmp_dfovec_1d_00150 = tmp_x_00113**2
        g_tmp_dfovec_1d_00151 = g_tmp_dfovec_1d_00149 - g_tmp_dfovec_1d_00150
        tmp_dfovec_1d_00151 = tmp_dfovec_1d_00149 - tmp_dfovec_1d_00150
        g_tmp_dfovec_1d_00152 = g_tmp_x_00111 * tmp_dfovec_1d_00151 + tmp_x_00111 * g_tmp_dfovec_1d_00151
        tmp_dfovec_1d_00152 = tmp_x_00111 * tmp_dfovec_1d_00151
        g_tmp_x_00114 = g_x[0]
        tmp_x_00114 = x[0]
        g_tmp_dfovec_1d_00153 = 2.0 * g_tmp_x_00114 * tmp_x_00112 * tmp_x_00113 + 2.0 * tmp_x_00114 * g_tmp_x_00112 * tmp_x_00113 + 2.0 * tmp_x_00114 * tmp_x_00112 * g_tmp_x_00113
        tmp_dfovec_1d_00153 = 2.0 * tmp_x_00114 * tmp_x_00112 * tmp_x_00113
        g_tmp_x_00115 = g_x[3]
        tmp_x_00115 = x[3]
        g_tmp_x_00116 = g_x[5]
        tmp_x_00116 = x[5]
        g_tmp_dfovec_1d_00154 = adimat_g_pow_left(g_tmp_x_00116, tmp_x_00116, 2)[0]
        tmp_dfovec_1d_00154 = tmp_x_00116**2
        g_tmp_x_00117 = g_x[7]
        tmp_x_00117 = x[7]
        g_tmp_dfovec_1d_00155 = adimat_g_pow_left(g_tmp_x_00117, tmp_x_00117, 2)[0]
        tmp_dfovec_1d_00155 = tmp_x_00117**2
        g_tmp_dfovec_1d_00156 = g_tmp_dfovec_1d_00154 - g_tmp_dfovec_1d_00155
        tmp_dfovec_1d_00156 = tmp_dfovec_1d_00154 - tmp_dfovec_1d_00155
        g_tmp_dfovec_1d_00157 = g_tmp_x_00115 * tmp_dfovec_1d_00156 + tmp_x_00115 * g_tmp_dfovec_1d_00156
        tmp_dfovec_1d_00157 = tmp_x_00115 * tmp_dfovec_1d_00156
        g_tmp_x_00118 = g_x[1]
        tmp_x_00118 = x[1]
        g_tmp_dfovec_1d_00158 = 2.0 * g_tmp_x_00118 * tmp_x_00116 * tmp_x_00117 + 2.0 * tmp_x_00118 * g_tmp_x_00116 * tmp_x_00117 + 2.0 * tmp_x_00118 * tmp_x_00116 * g_tmp_x_00117
        tmp_dfovec_1d_00158 = 2.0 * tmp_x_00118 * tmp_x_00116 * tmp_x_00117
        g_fvec[5] = g_tmp_dfovec_1d_00152 + g_tmp_dfovec_1d_00153 + g_tmp_dfovec_1d_00157 + g_tmp_dfovec_1d_00158
        fvec[5] = tmp_dfovec_1d_00152 + tmp_dfovec_1d_00153 + tmp_dfovec_1d_00157 + tmp_dfovec_1d_00158 - 2.0
        g_tmp_x_00119 = g_x[0]
        tmp_x_00119 = x[0]
        g_tmp_x_00120 = g_x[4]
        tmp_x_00120 = x[4]
        g_tmp_dfovec_1d_00159 = adimat_g_pow_left(g_tmp_x_00120, tmp_x_00120, 2)[0]
        tmp_dfovec_1d_00159 = tmp_x_00120**2
        g_tmp_x_00121 = g_x[6]
        tmp_x_00121 = x[6]
        g_tmp_dfovec_1d_00160 = adimat_g_pow_left(g_tmp_x_00121, tmp_x_00121, 2)[0]
        tmp_dfovec_1d_00160 = tmp_x_00121**2
        g_tmp_dfovec_1d_00161 = 3.0 * g_tmp_dfovec_1d_00160
        tmp_dfovec_1d_00161 = 3.0 * tmp_dfovec_1d_00160
        g_tmp_dfovec_1d_00162 = g_tmp_dfovec_1d_00159 - g_tmp_dfovec_1d_00161
        tmp_dfovec_1d_00162 = tmp_dfovec_1d_00159 - tmp_dfovec_1d_00161
        g_tmp_dfovec_1d_00163 = g_tmp_x_00119 * tmp_x_00120 * tmp_dfovec_1d_00162 + tmp_x_00119 * g_tmp_x_00120 * tmp_dfovec_1d_00162 + tmp_x_00119 * tmp_x_00120 * g_tmp_dfovec_1d_00162
        tmp_dfovec_1d_00163 = tmp_x_00119 * tmp_x_00120 * tmp_dfovec_1d_00162
        g_tmp_x_00122 = g_x[2]
        tmp_x_00122 = x[2]
        g_tmp_dfovec_1d_00164 = 3.0 * g_tmp_dfovec_1d_00159
        tmp_dfovec_1d_00164 = 3.0 * tmp_dfovec_1d_00159
        g_tmp_dfovec_1d_00165 = g_tmp_dfovec_1d_00160 - g_tmp_dfovec_1d_00164
        tmp_dfovec_1d_00165 = tmp_dfovec_1d_00160 - tmp_dfovec_1d_00164
        g_tmp_dfovec_1d_00166 = g_tmp_x_00122 * tmp_x_00121 * tmp_dfovec_1d_00165 + tmp_x_00122 * g_tmp_x_00121 * tmp_dfovec_1d_00165 + tmp_x_00122 * tmp_x_00121 * g_tmp_dfovec_1d_00165
        tmp_dfovec_1d_00166 = tmp_x_00122 * tmp_x_00121 * tmp_dfovec_1d_00165
        g_tmp_x_00123 = g_x[1]
        tmp_x_00123 = x[1]
        g_tmp_x_00124 = g_x[5]
        tmp_x_00124 = x[5]
        g_tmp_dfovec_1d_00167 = adimat_g_pow_left(g_tmp_x_00124, tmp_x_00124, 2)[0]
        tmp_dfovec_1d_00167 = tmp_x_00124**2
        g_tmp_x_00125 = g_x[7]
        tmp_x_00125 = x[7]
        g_tmp_dfovec_1d_00168 = adimat_g_pow_left(g_tmp_x_00125, tmp_x_00125, 2)[0]
        tmp_dfovec_1d_00168 = tmp_x_00125**2
        g_tmp_dfovec_1d_00169 = 3.0 * g_tmp_dfovec_1d_00168
        tmp_dfovec_1d_00169 = 3.0 * tmp_dfovec_1d_00168
        g_tmp_dfovec_1d_00170 = g_tmp_dfovec_1d_00167 - g_tmp_dfovec_1d_00169
        tmp_dfovec_1d_00170 = tmp_dfovec_1d_00167 - tmp_dfovec_1d_00169
        g_tmp_dfovec_1d_00171 = g_tmp_x_00123 * tmp_x_00124 * tmp_dfovec_1d_00170 + tmp_x_00123 * g_tmp_x_00124 * tmp_dfovec_1d_00170 + tmp_x_00123 * tmp_x_00124 * g_tmp_dfovec_1d_00170
        tmp_dfovec_1d_00171 = tmp_x_00123 * tmp_x_00124 * tmp_dfovec_1d_00170
        g_tmp_x_00126 = g_x[3]
        tmp_x_00126 = x[3]
        g_tmp_dfovec_1d_00172 = 3.0 * g_tmp_dfovec_1d_00167
        tmp_dfovec_1d_00172 = 3.0 * tmp_dfovec_1d_00167
        g_tmp_dfovec_1d_00173 = g_tmp_dfovec_1d_00168 - g_tmp_dfovec_1d_00172
        tmp_dfovec_1d_00173 = tmp_dfovec_1d_00168 - tmp_dfovec_1d_00172
        g_tmp_dfovec_1d_00174 = g_tmp_x_00126 * tmp_x_00125 * tmp_dfovec_1d_00173 + tmp_x_00126 * g_tmp_x_00125 * tmp_dfovec_1d_00173 + tmp_x_00126 * tmp_x_00125 * g_tmp_dfovec_1d_00173
        tmp_dfovec_1d_00174 = tmp_x_00126 * tmp_x_00125 * tmp_dfovec_1d_00173
        g_fvec[6] = g_tmp_dfovec_1d_00163 + g_tmp_dfovec_1d_00166 + g_tmp_dfovec_1d_00171 + g_tmp_dfovec_1d_00174
        fvec[6] = tmp_dfovec_1d_00163 + tmp_dfovec_1d_00166 + tmp_dfovec_1d_00171 + tmp_dfovec_1d_00174 + 12.6
        g_tmp_x_00127 = g_x[2]
        tmp_x_00127 = x[2]
        g_tmp_x_00128 = g_x[4]
        tmp_x_00128 = x[4]
        g_tmp_dfovec_1d_00175 = adimat_g_pow_left(g_tmp_x_00128, tmp_x_00128, 2)[0]
        tmp_dfovec_1d_00175 = tmp_x_00128**2
        g_tmp_x_00129 = g_x[6]
        tmp_x_00129 = x[6]
        g_tmp_dfovec_1d_00176 = adimat_g_pow_left(g_tmp_x_00129, tmp_x_00129, 2)[0]
        tmp_dfovec_1d_00176 = tmp_x_00129**2
        g_tmp_dfovec_1d_00177 = 3.0 * g_tmp_dfovec_1d_00176
        tmp_dfovec_1d_00177 = 3.0 * tmp_dfovec_1d_00176
        g_tmp_dfovec_1d_00178 = g_tmp_dfovec_1d_00175 - g_tmp_dfovec_1d_00177
        tmp_dfovec_1d_00178 = tmp_dfovec_1d_00175 - tmp_dfovec_1d_00177
        g_tmp_dfovec_1d_00179 = g_tmp_x_00127 * tmp_x_00128 * tmp_dfovec_1d_00178 + tmp_x_00127 * g_tmp_x_00128 * tmp_dfovec_1d_00178 + tmp_x_00127 * tmp_x_00128 * g_tmp_dfovec_1d_00178
        tmp_dfovec_1d_00179 = tmp_x_00127 * tmp_x_00128 * tmp_dfovec_1d_00178
        g_tmp_x_00130 = g_x[0]
        tmp_x_00130 = x[0]
        g_tmp_dfovec_1d_00180 = 3.0 * g_tmp_dfovec_1d_00175
        tmp_dfovec_1d_00180 = 3.0 * tmp_dfovec_1d_00175
        g_tmp_dfovec_1d_00181 = g_tmp_dfovec_1d_00176 - g_tmp_dfovec_1d_00180
        tmp_dfovec_1d_00181 = tmp_dfovec_1d_00176 - tmp_dfovec_1d_00180
        g_tmp_dfovec_1d_00182 = g_tmp_x_00130 * tmp_x_00129 * tmp_dfovec_1d_00181 + tmp_x_00130 * g_tmp_x_00129 * tmp_dfovec_1d_00181 + tmp_x_00130 * tmp_x_00129 * g_tmp_dfovec_1d_00181
        tmp_dfovec_1d_00182 = tmp_x_00130 * tmp_x_00129 * tmp_dfovec_1d_00181
        g_tmp_x_00131 = g_x[3]
        tmp_x_00131 = x[3]
        g_tmp_x_00132 = g_x[5]
        tmp_x_00132 = x[5]
        g_tmp_dfovec_1d_00183 = adimat_g_pow_left(g_tmp_x_00132, tmp_x_00132, 2)[0]
        tmp_dfovec_1d_00183 = tmp_x_00132**2
        g_tmp_x_00133 = g_x[7]
        tmp_x_00133 = x[7]
        g_tmp_dfovec_1d_00184 = adimat_g_pow_left(g_tmp_x_00133, tmp_x_00133, 2)[0]
        tmp_dfovec_1d_00184 = tmp_x_00133**2
        g_tmp_dfovec_1d_00185 = 3.0 * g_tmp_dfovec_1d_00184
        tmp_dfovec_1d_00185 = 3.0 * tmp_dfovec_1d_00184
        g_tmp_dfovec_1d_00186 = g_tmp_dfovec_1d_00183 - g_tmp_dfovec_1d_00185
        tmp_dfovec_1d_00186 = tmp_dfovec_1d_00183 - tmp_dfovec_1d_00185
        g_tmp_dfovec_1d_00187 = g_tmp_x_00131 * tmp_x_00132 * tmp_dfovec_1d_00186 + tmp_x_00131 * g_tmp_x_00132 * tmp_dfovec_1d_00186 + tmp_x_00131 * tmp_x_00132 * g_tmp_dfovec_1d_00186
        tmp_dfovec_1d_00187 = tmp_x_00131 * tmp_x_00132 * tmp_dfovec_1d_00186
        g_tmp_x_00134 = g_x[1]
        tmp_x_00134 = x[1]
        g_tmp_dfovec_1d_00188 = 3.0 * g_tmp_dfovec_1d_00183
        tmp_dfovec_1d_00188 = 3.0 * tmp_dfovec_1d_00183
        g_tmp_dfovec_1d_00189 = g_tmp_dfovec_1d_00184 - g_tmp_dfovec_1d_00188
        tmp_dfovec_1d_00189 = tmp_dfovec_1d_00184 - tmp_dfovec_1d_00188
        g_tmp_dfovec_1d_00190 = g_tmp_x_00134 * tmp_x_00133 * tmp_dfovec_1d_00189 + tmp_x_00134 * g_tmp_x_00133 * tmp_dfovec_1d_00189 + tmp_x_00134 * tmp_x_00133 * g_tmp_dfovec_1d_00189
        tmp_dfovec_1d_00190 = tmp_x_00134 * tmp_x_00133 * tmp_dfovec_1d_00189
        g_fvec[7] = g_tmp_dfovec_1d_00179 - g_tmp_dfovec_1d_00182 + g_tmp_dfovec_1d_00187 - g_tmp_dfovec_1d_00190
        fvec[7] = tmp_dfovec_1d_00179 - tmp_dfovec_1d_00182 + tmp_dfovec_1d_00187 - tmp_dfovec_1d_00190 - 9.48
    return g_fvec, fvec
